config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'

  resources :posts do
    collection do
      get 'search'
    end
  end

  get '/users/:user_id/likes' => "likes#show"
  post '/posts/:post_id/likes' => "likes#create"
  delete '/posts/:post_id/likes' => "likes#destroy"

  get '/searcharea/europe' => 'posts#search_europe'
  get '/searcharea/africa' => 'posts#search_africa'
  get '/searcharea/northamerica' => 'posts#search_northamerica'
  get '/searcharea/latinamerica' => 'posts#search_latinamerica'
  get '/searcharea/asia' => 'posts#search_asia'
  get '/searcharea/oceania' => 'posts#search_oceania'
  get '/searcharea/middleeast' => 'posts#search_middleeast'



  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_one_attached :image
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  scope :recent, -> { order("created_at DESC")}

  scope :europe, -> { where(country: ["208", "250", "528", "578", "643", "724", "752", "826"]) }
  scope :africa, -> { where(country: ["710, 818"]) }
  scope :north_america, -> { where(country: ["124", "840"]) }
  scope :latain_america, -> { where(country: ["032","076", "152"]) }
  scope :asia, -> { where(country: ["156", "158", "344", "392", "410", "702", "764"]) }
  scope :oceania, -> { where(country: ["036", "316",  "554"]) }
  scope :middle_east, -> { where(country: ["682", "792"]) }


  enum duration: [:in_two_days, :in_three_days, :in_five_days, :in_seven_days,  :in_two_weeks, :in_a_month, :in_three_months, :in_six_months, :in_a_year, :over_a_year]

  validates :image, presence: true
  validates :text, {presence: true, length: {maximum: 10000}}
  validates :country, presence: true
  validates :duration, presence: true



  def like?(user)
    liked_users.include?(user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :name, presence: true, length: { maximum: 6}

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :request_path

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


  def request_path
    @path = controller_path + '#' + action_name
      def @path.is(*str)
          str.map{|s| self.include?(s)}.include?(true)
      end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def show
    @name = current_user.name
    @liked_posts = current_user.liked_posts.page(params[:page]).per(6)
  end

  def create
    @like = Like.create(user_id: current_user.id, post_id: @post.id)
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
    @like.destroy
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :search, :search_europe, :search_africa, :search_northamerica, :search_latainamerica, :search_asia, :search_oceania, :search_middleeast]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_countries, onle: [:new, :create, :edit, :update]

  def index
    @posts = Post.recent.page(params[:page]).per(6)

    @sidebarAreas = 
      [{area:"Europe", kana:"ヨーロッパ", link: "/searcharea/europe"},
      {area:"Africa", kana:"アフリカ", link: "/searcharea/africa"},
      {area:"North America", kana:"北アメリカ", link: "/searcharea/northamerica"},
      {area:"Latin America", kana:"ラテンアメリカ", link: "/searcharea/latinamerica"},
      {area:"Asia", kana:"アジア", link: "/searcharea/asia"},
      {area:"Oceania & Pacific Ocean", kana:"オセアニア＆太平洋", link: "/searcharea/oceania"},
      {area:"Middle East", kana:"中東", link: "/searcharea/middleeast"},
      {area:"All Over The World", kana:"世界各地", link: search_posts_path}]


      tour_areas = ["AAS", "BCH", "HWI", "EUR", "DUS", "FOC", "CAF"]
      @tour_area = tour_areas.sample
      uri = "http://webservice.recruit.co.jp/ab-road/tour/v1/?" + 
        "key=#{ENV['TRAVEL_APIKEY']}&" + "area=#{@tour_area}&" + "format=json"

      uri = URI.parse(uri)
      req = Net::HTTP::Get.new(uri)
      res = Net::HTTP.start(uri.host, uri.port){|http|
        http.request(req)
      }
      @tour_result = JSON.parse(res.body)
      @tour_image = @tour_result["results"]["tour"][0]["img"][0]["l"]
      @tour_link = @tour_result["results"]["tour"][0]["urls"]["pc"]
      @tour_title = @tour_result["results"]["tour"][0]["title"]
      @min_price = @tour_result["results"]["tour"][0]["price"]["min"]
      @max_price = @tour_result["results"]["tour"][0]["price"]["max"]
  end

  def show
    @country = ISO3166::Country.find_country_by_number(@post.country)
  end
  
  def new
    @post = Post.new
  end

  def create
    @post= Post.new(post_params)
      if @post.save
        flash[:notice] = "投稿が完了しました！"
        redirect_to posts_path
      else
        flash[:alert] = "投稿に失敗しました…"
        render new_post_path
      end
  end

  def edit
    if @post.user.id != current_user.id
      redirect_to posts_path
    end
  end

  def update
    if @post.user_id == current_user.id
      if @post.update(post_params)
        flash[:notice] = "更新しました"
        redirect_to controller: :posts, action: :index
      else
        flash[:alert] = "更新に失敗しました"
        render('posts/edit')
      end
    end
  end

  def destroy
    if @post.user_id == current_user.id
      if @post.destroy
        flash[:alert] = "削除しました"
        redirect_to posts_path
      else
        flash[:alert] = "削除に失敗しました"
        redirect_to post_path
      end
    end
  end

  def search
    @posts = Post.where('text LIKE(?)', "%#{params[:post]}%").recent.page(params[:page]).per(6)
  end

  def search_europe
    @posts = Post.europe.recent
  end

  def search_africa
    @posts = Post.africa.recent
  end

  def search_northamerica
    @posts = Post.north_america.recent
  end

  def search_latainamerica
    @posts = Post.latain_america.recent
  end

  def search_asia
    @posts = Post.asia.recent
  end

  def search_oceania
    @posts = Post.oceania.recent
  end

  def search_middleeast
    @posts = Post.middle_east.recent
  end

  private
  def post_params
    params.require(:post).permit(:text, :country, :duration, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_countries
    @countries = ISO3166::Country.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @name = current_user.name
    @posts = Post.where(user_id: current_user.id).page(params[:page]).per(6)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/top.html.haml
.main-wrapper
  .top-wrapper
    .home__top
      .home__top__container
        %h1 旅を探そう
        .home__top__container__btn
          = link_to "はじめる", posts_path, class: "grey-text darken-4"
    .home__center
      .home__center__container
        %h2 何ができるの？
        .row.home__center__container__boxes
          .col.s4.home__center__container__box 
            .home__center__container__box__icon
              %i.material-icons photo_camera
            .home__center__container__box__heading
              のこす
            .home__center__container__box__text
              %p 旅の思い出を写真と文章で残そう。
              %p とっておきの旅を教えてください。
          .col.s4.home__center__container__box
            .home__center__container__box__icon
              %i.material-icons search
            .home__center__container__box__heading
              さがす
            .home__center__container__box__text
              %p 好きなキーワードで検索しよう。
              %p 気になる旅がきっと見つかるはず。
          .col.s4.home__center__container__box
            .home__center__container__box__icon
              %i.material-icons favorite_border
            .home__center__container__box__heading
              いいねする
            .home__center__container__box__text
              %p お気に入りの写真はいいねしよう。
              %p 後で見返すことができます。
    .home__bottom
      .home__bottom__container
        .home__bottom__container__text
          %p さあ、あなたも早速始めてみませんか？
        .home__bottom__container__btn
          = link_to "はじめる", posts_path, class: "white-text"

app/views/layouts/_flash.html.haml
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TravelApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css", :rel => "stylesheet"}/
    %link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css", :rel => "stylesheet"}/
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"}
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}



  %body
    %header
      %nav.light-blue.lighten-3
        .nav-wrapper
          = image_tag "Travel App.png", class: "header-pic"
          = link_to 'TravelApp', posts_path, class: "brand-logo"
          %ul#nav-mobile.right.hide-on-med-and-down
            - if user_signed_in?
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
              %li
                = link_to 'Mypage', user_path((current_user))
            - else
              %li
                = link_to 'Login', new_user_session_path, class: :post
              %li
                = link_to 'Signup', new_user_registration_path, class: :post

    = render 'layouts/flash'
    = yield

    %footer

app/views/likes/create.js.haml
$("#like-#{@post.id}").html(
"#{j(render partial: 'posts/like', locals: { post: @post })}"
);

app/views/likes/destroy.js.haml
$("#like-#{@post.id}").html(
"#{j(render partial: 'posts/like', locals: { post: @post })}"
);

app/views/likes/show.html.haml
.main__wrapper
  .mypage__top
    .mypage__top__name
      .mypage__top__all-posts
        = link_to "#{@name}さんの投稿一覧", "/users/#{current_user.id}", class: "grey-text lighten-1"
      .mypage__top__liked-posts
        = @name + "さんのいいね一覧"
  .post__main
    = render partial: 'posts/post', collection: @liked_posts
    
  = render partial: "shared/newposts_button"


  .pagination
    = paginate(@liked_posts)

app/views/posts/_form.html.haml
= form_with model: post, local: true do |f|
  .post__form
    .post__form__pic 
      %label.post__form__top 写真
      - if @post.errors.any?
        %p.post__form__error 写真を選択してください
      - if @path.is('posts#edit')
        .post__form__pic__preview
          = image_tag post.image, {style:"height: 400px; width: 612px;"}
      - else
        .post__form__pic__box#img_field{onclick: "$('#image__upload').click()"}
          %i.medium.material-icons add_a_photo
        .post__form__pic__preview__new
          %img#preview{style:"height: 400px; width: 612px;"}
        = f.file_field :image, id: "image__upload", style: "display: none;"
        .post__form__pic__preview__btn
          %p プレビューを削除

    .post__form__place
      %label.post__form__top 国
      - if @post.errors.any?
        %p.post__form__error 国を選択してください
      = f.collection_select :country, @countries, :number, :name, {prompt: '国を選んでください'}, class: "browser-default", id: "country_select"
    .post__form__duration
      %label.post__form__top 期間
      - if @post.errors.any?
        %p.post__form__error 期間を選択してください
      = f.select :duration, Post.durations_i18n.invert, {prompt: '期間を選んでください'}, class: "browser-default"
    .post__form__text
      %label.post__form__top 本文
      - if @post.errors.any?
        %p.post__form__error 本文を入力してください
      = f.text_area :text, class: "post__form__text__box"

    .post__form__btn
      = f.submit '送信', class: "btn waves-effect waves-light"

app/views/posts/_freespace__sidebar.html.haml
%li.freespace__sidebar__list
  = link_to(sidebarArea[:area], sidebarArea[:link])
  %span.freespace__sidebar__list__area 
    = sidebarArea[:kana]

app/views/posts/_like.html.haml
- if post.like?(current_user)
  = link_to "/posts/#{post.id}/likes", post: post, method: :delete, remote: true, class: "info_btn" do
    %i.material-icons favorite
- else
  = link_to "/posts/#{post.id}/likes", post: post, method: :post, remote: true, class: "info_btn" do
    %i.material-icons favorite_border

app/views/posts/_post.html.haml
.row
  .col.s12
    .image-top
      = ISO3166::Country.find_country_by_number(post.country).alpha3
      = ISO3166::Country.find_country_by_number(post.country).emoji_flag
    .card
      = link_to post_path(post, params: { post_id: params[:id]}) do
        .card-image
          = image_tag post.image
      .card-content
        %p
          = post.text
      .card-action
        = link_to "Show Detail", post_path(post, params: { post_id: params[:id]}), class: "deep-orange-text lighten-2"

app/views/posts/area_search.html.haml
.main__wrapper
  .post__search
    = render partial: 'post', collection: @posts

  .post__main__btn
    = link_to new_post_path, class: "btn-floating btn-large waves-effect waves-light red" do
      %i.material-icons add
      
  .pagination
  = paginate(@posts)

app/views/posts/edit.html.haml
.main__wrapper
  = render partial: 'form', locals: {post: @post} 

app/views/posts/search.html.haml
.main__wrapper
  .post__search
    - if @posts.present?
      = render partial: 'post', collection: @posts
    - else
      .post__search__noresult
        %p.post__search__noresult__message
          検索結果はありませんでした…
        %p.post__search__noresult__message
          キーワードを変えてみてね！

  = render partial: "shared/newposts_button"

  .pagination
  = paginate(@posts)

app/views/posts/search_asia.html.haml
.main__wrapper
  .post__area
    .post__area__top
      Asia
    .post__area__bottom
      アジア
  .post__search
    = render partial: 'post', collection: @posts

  = render partial: "shared/newposts_button"

app/views/posts/search_europe.html.haml
.main__wrapper
  .post__area
    .post__area__top
      Europe
    .post__area__bottom
      ヨーロッパ
  .post__search
    = render partial: 'post', collection: @posts

  = render partial: "shared/newposts_button"

      

app/views/posts/search_latinamerica.html.haml
.main__wrapper
  .post__area
    .post__area__top
      Latin America
    .post__area__bottom
      ラテンアメリカ
  .post__search
    = render partial: 'post', collection: @posts

  = render partial: "shared/newposts_button"

app/views/posts/search_middleeast.html.haml
.main__wrapper
  .post__area
    .post__area__top
      Middle East
    .post__area__bottom
      中東
  .post__search
    = render partial: 'post', collection: @posts

  = render partial: "shared/newposts_button"

app/views/posts/search_northamerica.html.haml
.main__wrapper
  .post__area
    .post__area__top
      North America
    .post__area__bottom
      北アメリカ
  .post__search
    = render partial: 'post', collection: @posts

  = render partial: "shared/newposts_button"

app/views/posts/search_oceania.html.haml
.main__wrapper
  .post__area
    .post__area__top
      Oceania & Pacific Ocean
    .post__area__bottom
      オセアニア＆太平洋
  .post__search
    = render partial: 'post', collection: @posts

  = render partial: "shared/newposts_button"

app/views/posts/show.html.haml
.main-wrapper
  .post__info
    .post__info__top
      = image_tag @post.image, class: "post__info__image"
      .post__info__sideinfo
        %ul.post__info__sideinfo__lists
          %li.post__info__sideinfo__list
            %label エリア
            .post__info__sideinfo__list-contents
            = @country.region
          %li.post__info__sideinfo__list
            %label 国
            .post__info__sideinfo__list-contents
            = @country.name
          %li.post__info__sideinfo__list
            %label 期間
            .post__info__sideinfo__list-contents
            = @post.duration_i18n
          %li.post__info__sideinfo__list
            %label ユーザー名
            .post__info__sideinfo__list-contents
            = @post.user.name
          - if user_signed_in?
            %li.post__info__sideinfo__lists#edit-list
              .post__info__sideinfo__lists__like{id: "like-#{@post.id}"}
                = render partial: "like", locals: {post: @post}
              - if user_signed_in? && current_user.id == @post.user.id
                .post__info__sideinfo__lists__edit
                  = link_to edit_post_path, class: "info_btn" do
                    %i.material-icons mode_edit
                .post__info__sideinfo__lists__delete
                  = link_to post_path(@post.id), method: :delete, data: {confirm: "削除しますか？"}, class: "info_btn" do
                    %i.material-icons delete
    .post__info__bottom
      .post__info__text
        = @post.text
    .post__info__btn
      = link_to "<もどる", posts_path

  = render partial: "shared/newposts_button"

app/views/shared/_newposts_button.html.haml
.post__main__btn
  = link_to new_post_path, class: "btn-floating btn-large waves-effect waves-light red" do
    %i.material-icons add

app/views/users/show.html.haml
.main__wrapper
  .mypage__top
    .mypage__top__name
      .mypage__top__posts
        = "#{@name}さんの投稿一覧"
      .mypage__top__posts
        = link_to "#{@name}さんのいいね一覧", "/users/#{current_user.id}/likes", class: "grey-text lighten-1"
  .post__main
    = render partial: 'posts/post', collection: @posts
    
  = render partial: "shared/newposts_button"


  .pagination
    = paginate(@posts)